### ISSUE TITLE
Is this solving the same problem as Kmonad?

### ISSUE THREAD

**Issue by kjs3** [philipl/evdevremapkeys#19]
Not that it's a problem, I'm just wondering if this is solving the same set of issues as [Kmonad](https://github.com/david-janssen/kmonad)? Both operate at the uinput level and should work with xorg/wayland/console.

**Comment by philipl** [comment]
Kmonad appears to not to handle mouse button remapping, which was one of my primary use-cases.

**Comment by kjs3** [comment]
Thanks, that's a useful difference to know.
