### ISSUE TITLE
Cann't remap graphic tablet tab

### ISSUE THREAD

**Issue by yuperi** [philipl/evdevremapkeys#2]
config file
devices:
- input_name: UC-Logic TABLET 1060N Pad
  output_name: remap-key1
  remappings:
    BTN_0:
    - KEY_A

evtest from keyboard
Testing ... (interrupt to exit)
Event: time 1508594324.007138, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1c
Event: time 1508594324.007138, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1508594324.007138, -------------- SYN_REPORT ------------
Event: time 1508594324.753322, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1e
Event: time 1508594324.753322, type 1 (EV_KEY), code 30 (KEY_A), value 1
Event: time 1508594324.753322, -------------- SYN_REPORT ------------
Event: time 1508594324.842891, type 4 (EV_MSC), code 4 (MSC_SCAN), value 1e
Event: time 1508594324.842891, type 1 (EV_KEY), code 30 (KEY_A), value 0

evtest from pad
Testing ... (interrupt to exit)
Event: time 1508594491.388204, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1508594491.388204, -------------- SYN_REPORT ------------
Event: time 1508594491.388281, type 1 (EV_KEY), code 30 (KEY_A), value 1
Event: time 1508594491.388281, -------------- SYN_REPORT ------------
Event: time 1508594491.526235, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1508594491.526235, -------------- SYN_REPORT ------------
Event: time 1508594491.526312, type 1 (EV_KEY), code 30 (KEY_A), value 0

**Comment by philipl** [comment]
It looks like what I'd expect. the MSC_SCAN events are device specific but most things ignore them. You haven't said what your problem is.

**Comment by yuperi** [comment]
When I press button on the pad, there is no appearing symbol "a"

**Comment by philipl** [comment]
There isn't much I can say. The evtest output looks correct, so it will depend on your environment as to whether it works; I don't even know what desktop environment or application you're trying to use.

**Comment by yuperi** [comment]
There is some problem with libinput
$ sudo libinput debug-events
libinput error: event8  - libinput error: UC-Logic TABLET 1060N Pad: libinput error: libinput bug: device does not meet tablet criteria. Ignoring this device.

$ sudo evtest
Select the device event number [0-21]: 8
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x5543 product 0x81 version 0x111
Input device name: "UC-Logic TABLET 1060N Pad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 256 (BTN_0)
    Event code 257 (BTN_1)
    Event code 258 (BTN_2)
    Event code 259 (BTN_3)
    Event code 260 (BTN_4)
    Event code 261 (BTN_5)
    Event code 262 (BTN_6)
    Event code 263 (BTN_7)
    Event code 264 (BTN_8)
    Event code 331 (BTN_STYLUS)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max        1
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max        1
    Event code 40 (ABS_MISC)
      Value      0
      Min        0
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1508601507.237220, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1508601507.237220, type 1 (EV_KEY), code 256 (BTN_0), value 1
Event: time 1508601507.237220, -------------- SYN_REPORT ------------
Event: time 1508601507.363201, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90001
Event: time 1508601507.363201, type 1 (EV_KEY), code 256 (BTN_0), value 0
Event: time 1508601507.363201, -------------- SYN_REPORT ------------

**Comment by philipl** [comment]
Well, that explains it. libinput doesn't think it can handle the device, so it ignores it. Remapping keys will not help here. You need to file a bug report with libinput and give them information about your tablet so they can support it.
