### ISSUE TITLE
[Question] Is it possible to adjust the sensitivity of repeating events?

### ISSUE THREAD

**Issue by wallace11** [philipl/evdevremapkeys#8]
I'm using a touchpad for which the default four-finger swipe (up/down) is for volume up and down. It means that an event is fired every movement continuously (no need to take the fingers down - much like a wheel function). 
I'm trying to remap this gesture to walk between browser tabs, however it's way to sensitive for my taste and one small swipe blasts through 3-4 tabs each time.
In other words, would it be possible to simulate a wheel-like button to act like a normal key?

I hope my explanation was clear enough.

Thanks.

**Comment by philipl** [comment]
Yes, it would be possible with enough work. You can look at the existing functionality for key repeat for the basic idea. Rather than doing 1:1 event mapping, you would trigger the repeat logic with an appropriate key repeat rate that is slower than 1:1.

**Comment by wallace11** [comment]
I've taken my time exploring all sorts of options, but no matter what I do, each swipe would register numerous events, and each of them is caught and remapped.
To explain this a little bit better, here's a result of a four-finger swipe, starting from the middle and stopping at 2/3 height of the track pad (fingers on track pad the whole time):
```
Event: time 1525790967.019901, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.019901, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.019901, -------------- SYN_REPORT ------------
Event: time 1525790967.027857, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.027857, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.027857, -------------- SYN_REPORT ------------
Event: time 1525790967.099845, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.099845, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.099845, -------------- SYN_REPORT ------------
Event: time 1525790967.107848, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.107848, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.107848, -------------- SYN_REPORT ------------
Event: time 1525790967.163879, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.163879, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.163879, -------------- SYN_REPORT ------------
Event: time 1525790967.171875, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.171875, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.171875, -------------- SYN_REPORT ------------
Event: time 1525790967.219925, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.219925, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.219925, -------------- SYN_REPORT ------------
Event: time 1525790967.235853, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.235853, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.235853, -------------- SYN_REPORT ------------
Event: time 1525790967.307852, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.307852, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.307852, -------------- SYN_REPORT ------------
Event: time 1525790967.315854, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.315854, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.315854, -------------- SYN_REPORT ------------
Event: time 1525790967.387852, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.387852, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.387852, -------------- SYN_REPORT ------------
Event: time 1525790967.395859, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.395859, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.395859, -------------- SYN_REPORT ------------
Event: time 1525790967.499851, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.499851, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.499851, -------------- SYN_REPORT ------------
Event: time 1525790967.507858, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.507858, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.507858, -------------- SYN_REPORT ------------
Event: time 1525790967.675857, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.675857, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.675857, -------------- SYN_REPORT ------------
Event: time 1525790967.683858, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.683858, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.683858, -------------- SYN_REPORT ------------
Event: time 1525790967.795931, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.795931, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1525790967.795931, -------------- SYN_REPORT ------------
Event: time 1525790967.811858, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00e9
Event: time 1525790967.811858, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1525790967.811858, -------------- SYN_REPORT ------------
```
Hope this helps better illustrating the situation.

Thanks in advance for your help.

**Comment by philipl** [comment]
I understand. My point is you want to decouple the 1:1 event mapping and rate limit it to only send 1 mapped event every N raw events or every N ms; one approach probably works better than the other.

**Comment by wallace11** [comment]
I finally got what you meant, and have been experimenting with a possible solution.
I actually couldn't decide what's the best way to implement this, so for starters, here's what I decided to do:
1. Add a `delay` option that is coupled with `code`.
2. `delay` and `repeat` cannot be used together (since they defeat the purpose of each other).
3. For the skipping methodology I used a global counter (since I didn't want to touch `handle_events()`). It fires an event only when it's equal to 1. Counter resets when equal to `delay`.
3. Skipping an input entirely seems to cause lots of problems (keys get stuck at `value=1`), so instead I assigned a `value=0`. 

Here's how the code looks: (I omitted the last `else` part, since it's unchanged)
```python
def remap_event(output, event, remappings):
    global REMAPPED_COUNT
    REMAPPED_COUNT += 1
    for remapping in remappings[event.code]:
        original_code = event.code
        event.code = remapping['code']
        event.type = remapping.get('type', None) or event.type
        values = remapping.get('value', None) or [event.value]
        repeat = remapping.get('repeat', False)
        delay = remapping.get('delay', None)
        delay = delay if not delay or delay % 2 == 0 else delay + 1 # Making sure it's an even number
        if not repeat and not delay:
            for value in values:
                event.value = value
                output.write_event(event)
                output.syn()
        elif delay:
            if REMAPPED_COUNT == 1:
                event.value = 1
            else:
                REMAPPED_COUNT = 0 if REMAPPED_COUNT == delay else REMAPPED_COUNT
                event.value = 0
            output.write_event(event)
            output.syn()
```
This is very rough and I hope you'd provide me with your input to make it better.

Thanks.

**Comment by philipl** [comment]
Hi. Sorry for being slow to respond; it's been hard to find the time to think about this.

I think your basic approach makes sense - you are waiting for a certain number of input events before you generate an output event. The main issue is the global, of course. You should replace this with a dict where each entry contains enough information to do a lookup when an input event occurs and get the current count value. It's probably enough to use the event.code as the dict key and the count is the value.

So, when you get an event, you see if there's a current count. If there is no count, you create an entry in the dict at the delay value, and you probably emit the first output event immediately, and the delay will be for the second event. Then, on each subsequent input event, you do a look up. If it's there, you decrement the counter and continue. Eventually, the counter will reach zero, and you emit and reset the counter.

Now, this scheme has an issue where entries are never really removed from the dict. But in practice, you will never register more than a couple of these kinds of remappings, so it's fine for the dict to have 'n' entries forever where you have 'n' delay remappings.

As for not being able to skip sending an output event - you do need to send a '0' after the '1' but after you've sent a '0', you don't need to keeping sending '0'. If you want, you can add more state to the dict to track if you still need to send the '0'. I think this is better, as you then don't send a continuous stream of '0' events which seems ugly.

Finally, I would make 'delay' a boolean flag and use the 'count' property to decide how many events to wait for. This makes it more symmetric with the 'repeat' logic.
